# Netlify configuration file for blackforestlive repository

[build]
  # Base directory for the build (relative to the repository root)
  base = "frontend"

  # Command to build the Next.js app
  command = "npm run build"

  # Directory where the built files are output (relative to the base directory)
  publish = ".next"

  # Environment variables for the build
  [build.environment]
    NODE_VERSION = "18.19.0"

# Enable the Next.js plugin for SSR, API routes, and other features
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Optional: Development settings for Netlify Dev (local development)
[dev]
  command = "npm run dev"
  port = 8888
